### PR TITLE
Feature/#87 hook up query into sidebar

### PR DESCRIPTION
**Pull request by serpient**
### Test Render
image

### This PR does the following
- hook up the sidebar to a query that looks for the user's teams and render it appropriately in the sidebar
- extract the newsfeed component and sidebar component into separate items
- adjust styling on overall newsfeed page and sidebar

### CODE REVIEW

**Comment by the-vampiire** [comment]
this was changed in the final PR. @thinktwice13 changed it to be more explicit. `loader` is now called `globalLoader` as a `<Request>` boolean prop. and `toggleLoader()` is now `toggleGlobalLoader()` from the `/utilities` directory

**Comment by serpient** [comment]
the problem is still that its not resolving to error component?

**Comment by thinktwice13** [comment]
Bugfix here: https://github.com/luoto/chingu-frontend/pull/95

I'm looking into the loader vs error issue, but essentially, any query that comes in with an error turns the global loader flag to `false`.

**Comment by serpient** [comment]
will merge into the sprint branch because the request component works now that the query has been updated to have an `id`. the query/error-modal issue is separate.

**Pull request merged**
